name: KernelSU_iOS
options:
  bundleIdPrefix: me.weishu
targets:
  KernelSU_iOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        NSFaceIDUsageDescription: "Authentication is required to access KernelSU."
    settings:
      base:
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_ALLOWED: "NO"
